#ifndef KRITIC_ASSERT_TYPES_H
#define KRITIC_ASSERT_TYPES_H

typedef enum kritic_assert_type_t {
    KRITIC_ASSERT_UNKNOWN = 0,
    KRITIC_ASSERT,
    KRITIC_ASSERT_NOT,
    KRITIC_ASSERT_EQ_INT,
    KRITIC_ASSERT_EQ_FLOAT,
    KRITIC_ASSERT_EQ_STR,
    KRITIC_ASSERT_NE_INT,
    KRITIC_ASSERT_NE_FLOAT,
    KRITIC_ASSERT_NE_STR,
    KRITIC_ASSERT_FAIL
} kritic_assert_type_t;

#endif // KRITIC_ASSERT_TYPES_H
