name: Build & Release KritiC

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Clang
      run: sudo apt update && sudo apt install -y clang mingw-w64
    - name: Create compressed tarball
      run: make release       
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        name: KritiC ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: build/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
