name: Tag Workflow Chain

on:
  push:
    tags:
      - 'v*'

jobs:
  call-unittest:
    uses: ./.github/workflows/unittest.yml

  call-bump:
    needs: call-unittest
    uses: ./.github/workflows/bump-version.yml

  call-release:
    needs: call-bump
    uses: ./.github/workflows/release.yml
