name: Unittest

on:
  workflow_call:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - 'Makefile'
      - '.github/workflows/unittest.yml'
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
      - 'Makefile'
      - '.github/workflows/unittest.yml'

jobs:
  compare-selftest-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure project
        run: cmake -B build .
      - name: Build project
        run: make -C build
      - name: Run tests
        run: cd build && ctest
